### ISSUE TITLE
proposed new README.md for landing page

### ISSUE THREAD

**Issue by cstoeckert** [PennTURBO/med_mapping#27]
Propose updating README.md with the following. If OK, I can edit the file and do a PR.

The TURBO Medication Mapper (TMM) pipeline is a set a R scripts that take medication strings as input, learns associations to RxNorm entries, and outputs a RDF knowledge graph of associations based on the identified RxNorm entries and related entries in terminologies covering drugs and chemicals. A Solr database is made for searching the knowledge graph with the medication strings. An associated TMM Ontology provides structured documentation of the different types of entities that can be retrieved and the SPARQL queries to perform the retrieval from the knowledge graph.

The TURBO Medication Mapper is described in an ICBO 2020 paper “A Robust, Self-Training Classifier for Medication Strings, with Quantitative and Semantic Confidence Metrics” Mark A. Miller, Hayden Freedman, Christian J. Stoeckert, Jr. (supplemental files are located here).

The pipeline steps are:

1.	Extract medication strings (full name, generic name), associated database primary key, associated RxNorm codes
   a.	Filter for minimum number of patients with orders for the medication
   b.	Normalize strings: scrub and replace tokens
2.	Use the RxNav approximate search API to search extracted strings against all medications known to RxNav-in-a-Box
   a.	Submit normalized string to RxNav and receive candidate matches with ranks and scores based on the Jaccard index between the tokens in the input and those in in the matches. 
3.	Train a TTM model: Learn RxNorm with Random Forests.
   a.	TMM adds features like multiple string similarity measures between the inputs and matches, rxcui.count, the semantic type of the matching RxNorm term, and the upstream source from which RxNorm obtained the match’s label or synonyms.
4.	Classify medication strings with a trained TTM model
   a.	Interpret the features as predictors of the semantic relations between searches and matches
   b.	Classify matches as identical, related, more distant
5.	Convert matches and classifications to RDF with ROBOT
6.	Assemble a Medication Knowledge Graph
   a.	Creating mappings with RxNorm, DrOn, ChEBI, ATC, NDF-RT. Use BioPortal.
   b.	Generate RDF version
7.	Load the classification output, the BioPortal mappings, and additional ontologies/RDF models into a Graph DB repository to create the RDF knowledge graph.
8.	Create Solr core from with the labels and URIs of the entities in the ontologies and RDF data models.

**Comment by turbomam** [comment]
This content is good, but the ordering isn't quite right. Let me know if this slide helps.

[tmm_dependency_vs_proposed_readme.pptx](https://github.com/PennTURBO/medication-knowledgegraph-pipeline/files/5425721/tmm_dependency_vs_proposed_readme.pptx)

**Comment by cstoeckert** [comment]
Improved the pipeline steps text based on the powerpoint slide:
The pipeline steps are:
1. Train a TTM model: Learn RxNorm with Random Forests. Can reuse output of this step and start at step 2. [rxnav_med_mapping_proximity_training_no_tuning.R]
   a. TMM adds features like multiple string similarity measures between the inputs and matches, rxcui.count, the semantic type of the matching RxNorm term, and the upstream source from which RxNorm obtained the match’s label or synonyms.
   b. Steps are:
      i. submit random RxNorm labels to RxNav approximate search and get query/result pairs with scores and ranks
      ii. searches RxNorm SQL to determine the actual relationship between each pair (identical, off by one relation, or more distant)
      iii. calculate string distance between each query and result, along with other features for training
      iv. train a single-label, multi-class random forest classifier to determine relationships based on RxNav score, RxNav rank, string distances, etc
2. Extract medication strings (full name, generic name), associated database primary key, associated RxNorm codes, number of patients with orders for the medication. [pds_r_medication_sql_select.R output is an .Rdata file]
   a. Filter for minimum number of patients with orders for the medication [rxnav_med_mapping_proximity_classifier.R]
   b. Normalize strings: scrub and replace tokens [rxnav_med_mapping_proximity_classifier.R]
3. Use the RxNav approximate search API to search extracted strings against all medications known to RxNav-in-a-Box [rxnav_med_mapping_proximity_classifier.R]
   a. Submit normalized string to RxNav and receive candidate matches with ranks and scores based on the Jaccard index between the tokens in the input and those in in the matches. 
4. Classify medication strings with a trained TTM model [rxnav_med_mapping_proximity_classifier.R]
   a. Interpret the features as predictors of the semantic relations between searches and matches
   b. Classify matches as identical, related, more distant
5. Convert matches and classifications to RDF with ROBOT. [tmm_robot.sh]
6. Retrieve pairwise mappings between ChEBI, DrOn and RxNorm from BioPortal and save as a local RDF file. Can skip this step and reuse mappings until want to update source ontologies. [serialize_bioportal_mappings.R]
7. Assemble a Medication Knowledge Graph
   a. Load the classification output, the BioPortal mappings, and additional ontologies/RDF models into a Graph DB repository to create the RDF knowledge graph. [rxnav_med_mapping_load_materialize_etc.]
8. Create Solr core from with the labels and URIs of the entities in the ontologies and RDF data models. [build_insert_med_mapping_solr_json.R]

**Comment by turbomam** [comment]
This revision does a better job of describing the TURBO medication mapping steps, given the limitations of a linear narrative/outline.

The language in 1.b.i and 3.a should be much more similar because the exact same thing is happening in both of those steps. The only differences are the inputs and the objectives (training vs classifying)

**Comment by cstoeckert** [comment]
How's this?
1.b.i. Submit random RxNorm labels to RxNav approximate search and get query/result pairs with scores and ranks based on the Jaccard index between the tokens in the input and those in in the matches.

3.a. Submit normalized string to RxNav approximate search and get query/result pairs with scores and ranks based on the Jaccard index between the tokens in the input and those in in the matches.

**Comment by cstoeckert** [comment]
Updated directly to master
